# Generated by Django 3.1.2 on 2020-11-26 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0005_delete_place_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('isActive', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(default=datetime.datetime(2020, 11, 26, 10, 46, 33, 879498), editable=False)),
            ],
        ),
    ]
