# Generated by Django 3.1.2 on 2020-11-26 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 14, 49, 54, 561855), editable=False),
        ),
    ]
