# Generated by Django 3.1.2 on 2020-11-27 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20201126_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 11, 55, 57, 534439), editable=False),
        ),
        migrations.CreateModel(
            name='airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('seats', models.IntegerField(default=30)),
                ('added_date', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 11, 55, 57, 534439), editable=False)),
                ('which_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.airline')),
            ],
        ),
    ]
