# Generated by Django 3.1.2 on 2020-11-27 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201127_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline_staff',
            old_name='which_airline',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='airline_staff',
            old_name='which_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='airplane',
            old_name='which_airline',
            new_name='airline',
        ),
        migrations.AlterField(
            model_name='airline',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 12, 8, 43, 89652), editable=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 12, 8, 43, 89652), editable=False),
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_num', models.IntegerField(default=30)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('upcoming', 'upcoming'), ('in progress', 'in progress'), ('delayed', 'delayed')], default='upcoming', max_length=150)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.airline')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.airplane')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Arrival', to='application.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Departure', to='application.airport')),
            ],
        ),
    ]
