# Generated by Django 3.1.2 on 2020-11-27 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20201127_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='model',
            new_name='model_year',
        ),
        migrations.AlterField(
            model_name='airline',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 12, 37, 16, 803009), editable=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 12, 37, 16, 811010), editable=False),
        ),
    ]
