# Generated by Django 3.1.2 on 2020-11-27 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20201127_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 12, 45, 32, 553319), editable=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 12, 45, 32, 553319), editable=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_num',
            field=models.IntegerField(),
        ),
    ]
