# Generated by Django 3.0.3 on 2020-12-03 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20201203_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseticket',
            name='customer_email',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='airline',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 19, 8, 16, 171140), editable=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 19, 8, 16, 172139), editable=False),
        ),
    ]
