# Generated by Django 3.0.3 on 2020-12-04 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_auto_20201203_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 18, 11, 45, 441795), editable=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 18, 11, 45, 442794), editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseticket',
            unique_together=set(),
        ),
    ]
