# Generated by Django 3.0.3 on 2020-12-08 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20201208_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseticket',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 14, 6, 15, 84682), editable=False),
        ),
        migrations.AlterField(
            model_name='airline',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 14, 6, 15, 84682), editable=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 14, 6, 15, 84682), editable=False),
        ),
    ]
